name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.22.0
        check-latest: true
        cache: false
  
    - name: Build
      run: go build ./...

    - name: Gosec
      uses: securego/gosec@master
      with:
        args: ./...

    - name: Test
      run: go test -v ./...

    # ensure that the K4 analysis exits
    # without any error
    - name: Run K4 Analysis
      run: go run ./...
